// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Agendamentos.API.Map;

public partial class desafioContext : DbContext
{
    public desafioContext(DbContextOptions<desafioContext> options)
        : base(options)
    {
    }

    public virtual DbSet<tb_agendamento> tb_agendamentos { get; set; }

    public virtual DbSet<tb_paciente> tb_pacientes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<tb_agendamento>(entity =>
        {
            entity.HasKey(e => e.id_agendamento).HasName("PK_TB_AGENDAMENTO");

            entity.ToTable("tb_agendamento");

            entity.Property(e => e.id_agendamento).ValueGeneratedNever();
            entity.Property(e => e.dat_agendamento).HasColumnType("date");
            entity.Property(e => e.dat_criacao).HasColumnType("datetime");
            entity.Property(e => e.dsc_status)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.id_pacienteNavigation).WithMany(p => p.tb_agendamentos)
                .HasForeignKey(d => d.id_paciente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_agendamento_paciente");
        });

        modelBuilder.Entity<tb_paciente>(entity =>
        {
            entity.HasKey(e => e.id_paciente).HasName("PK_TB_PACIENTE");

            entity.ToTable("tb_paciente");

            entity.Property(e => e.dat_criacao).HasColumnType("datetime");
            entity.Property(e => e.dat_nascimento).HasColumnType("datetime");
            entity.Property(e => e.dsc_nome)
                .IsRequired()
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}