// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Agendamentos.API.Map;

public partial class tb_agendamento
{
    public int id_agendamento { get; set; }

    public int id_paciente { get; set; }

    public DateTime dat_agendamento { get; set; }

    public TimeSpan hor_agendamento { get; set; }

    public string dsc_status { get; set; }

    public DateTime dat_criacao { get; set; }

    public virtual tb_paciente id_pacienteNavigation { get; set; }
}